### ISSUE TITLE
Any reason VortoValue is internal?

### ISSUE THREAD

**Issue by DanDiplo** [mattbrailsford/Vorto#11]
Great project!

It would be handy if the **VortoValue** model was public as for advanced tasks (such as creating content directly using the ContentService) this is necessary. Is there any reason why it's internal?

**Comment by mattbrailsford** [comment]
Just that's it not been tested for that purpose son don't want to make it public and have it not work, but then it can't be changed because it's public :)

Feel free to fork the code and make it public and test whether it works ok. I'm not not sure what it will do if you are wrapping a fairly complex datatype.
