### ISSUE TITLE
Custom URLs per language

### ISSUE THREAD

**Issue by alainvanderbroeck** [mattbrailsford/Vorto#17]
Hi @mattbrailsford 

The implementation of Vorto for all my input values was successfull.
Now i am trying to create alternative urls for pages in differrent languages, so the navigation-menu's and the links made on the website are picked from the translated Alternative url field.

I am a little bit in the dark here. Can you tell me what's the best approach on this?

Thanks in advance

**Comment by mattbrailsford** [comment]
Hey,

Unfortunately this is THE main drawback of 1:1 translation sites, all nodes must share the same URL so you can't provide language specific ones currently.

In theory it should be possible to hook into the umbraco request pipeline and work this out, but nobody has come up with a good solution of doing this. It is on my list to look at it at some point, however it is pretty low priority at the moment due to other commitments and this not being something I need myself right now.

I'm open to reviewing peoples solutions if someone wants to give it a try.

Matt

**Comment by AndrewDarby** [comment]
For reference, Jeroen Breuer has a Umbraco sample project and video overview to solve this issue,
using custom URLproviders
see https://our.umbraco.org/projects/developer-tools/1-1-multilingual-example/
https://www.youtube.com/watch?v=DWjbJiIUQdk

**Comment by alainvanderbroeck** [comment]
Thank you for your post. I will look into it!
